console.log("Ram" == "Shyam"); // false
console.log("Ram" == "ram"); // false
console.log("Ram" == "Ram"); // true
console.log(1 == "Ram"); // false
console.log(0 == 0); // true
console.log(0 == null); // false
console.log(0 == ""); // true
console.log(null == ""); // false
console.log(null == undefined); // true
